### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by rrrkkk** [jclc/tiralabra-compression#2]
1. Tehdyt toimenpiteet

Kloonattu repo 25.4.2017 klo 09:18
- päivitetty 27.4.2017 klo 09:53

Luettu:
- README.md
- aihemaarittely.md
- määrittelydokumentti.pdf
- toteutusdokumentti.pdf
- testausdokumentti.pdf
- viikkoraportit 1-5

Katsottu https://en.wikipedia.org/wiki/Lempel-Ziv-Welch

Yritetty kääntää README.md ohjeilla.

Käännetty komennoilla
mkdir build
cd src
g++ -I ../include -o ../build/tiracomp *.cpp

Ajettu
tiracomp -?
tiracomp -h

Katsottu main.cpp, encoder.cpp, *.hpp, decoder.cpp, input.cpp, output.cpp

Kokeiltu suoritusta
cd build
cp tiracomp foo
./tiracomp -v foo bar
./tiracomp -v bar foo
cmp foo tiracomp

2. Huomiot

2.1 Hyvää

Dokumentit ovat ymmärrettäviä ja selkeitä.

Koodi on sisennettyä.

Nimet on hyvin valittu.

Tiedostot on loogisesti nimetty.

Osaa pakata ja purkaa pakkauksen, tuottaen lopulta alkuperäisen kanssa
identtisen tiedoston; siis toimii :)

2.2 Kehitettävää

Jos ohjelman käynnistää tuntemattomalla optiolla, se voisi heti
tulostaa aputekstin (nyt: "Unknown option -?").

main.cpp, rivit 41-97:
Komentorivioptiot käydään läpi käsin. Voisi olla ymmärrettävämpää ja vähemmän
virheherkkää käyttää esimerkiksi getopt(3) - kirjastofunktiota apuna.

Useat apuluokat (esim. StringTable) on implementoitu inline-metodeina .hpp -
tiedostoissa. Vaihtoehtoinen käytäntö olisi kirjoittaa implementaatio
erilliseen .cpp - tiedostoon ja tehdä näistä kirjasto.

Ei kääntynyt ympäristössäni (Mac OS Sierra, Homebrew) annetuilla komennoilla.
- cmake keskeytyi virheilmoitukseen:
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
- make ei löydä makefile:ä

2.3 Mainintoja

Google Test oli uusi tuttavuus ja oppimiskäyrä oli vähän liian jyrkkä
kun se ei lähtenyt suoraan kukkumaan. Tämä on katselmoijan huonoutta
eikä projektin vika :)

**Comment by jclc** [comment]
Joo, CMake olettaa että GTest on asennettu pakettimanagerilla. Testit voi muutenkin disabloida ottamalla rastin pois MAKE_TESTS muuttujasta CMakella. Tämän olisi ehkä voinut kommunikoida paremmin käyttöohjeessa. StringTable ja BitBuffer on tehty inline-metodeilla tehokkuussyistä. Kiitos palautteesta.
